"""C-6/C-7 EQUIVALENCE GOLDEN — strict-superset / no silent weakening.

The C-2 lesson (a "byte-identical to legacy" docstring is not the same as
verified byte-identical behavior — Case 13 caught a silent unblocking) is the
hard rule for any security-boundary consolidation. This module captures the
LEGACY behavior of:

* :func:`magi_agent.sandbox.network.classify_network_url`
* :func:`magi_agent.web_acquisition.policy.is_blocked_ip`
* :func:`magi_agent.web_acquisition.policy.url_policy_error`

on a 20+-payload fixture set covering every legacy-fork edge case, and asserts
that the consolidated implementation produces:

* The SAME ``safe_host`` value on every URL.
* The SAME reason codes as a SUBSET of the new reason codes (strict-superset
  invariant — new reasons MAY be added on the NAT64 strengthening case, but
  no URL that was blocked before is unblocked).
* The SAME ``is_blocked_ip`` boolean on every IP.
* The SAME ``url_policy_error`` string on every URL.

Capture method: the legacy golden below was generated by running
``/tmp/capture_legacy_ssrf.py`` against the pre-C-6 codebase BEFORE any
``sandbox/network.py`` / ``web_acquisition/policy.py`` edits.
"""

from __future__ import annotations

import pytest


# Legacy golden — captured from the pre-C-6 codebase. Each entry is
# ``(url_or_host, expected_reasons_as_tuple)`` for ``classify_network_url``;
# expected_reasons in insertion order matching the legacy ``dict.fromkeys``
# de-duplication.
_CLASSIFY_GOLDEN: tuple[tuple[str, str | None, tuple[str, ...]], ...] = (
    ("http://0177.0.0.1/", "ip_host", ("private_network_blocked",)),
    ("http://017700000001/", "ip_host", ("private_network_blocked",)),
    ("http://0x7f000001/", "ip_host", ("private_network_blocked",)),
    ("http://0xa9fea9fe/", "ip_host", ("private_network_blocked",)),
    ("http://10.0.0.1/admin", "ip_host", ("private_network_blocked",)),
    ("http://127.0.0.1/", "ip_host", ("private_network_blocked",)),
    (
        "http://169.254.169.254/latest/meta-data",
        "ip_host",
        ("private_network_blocked", "metadata_endpoint_blocked"),
    ),
    ("http://172.16.0.1/internal", "ip_host", ("private_network_blocked",)),
    ("http://192.168.1.1/router", "ip_host", ("private_network_blocked",)),
    ("http://2130706433/", "ip_host", ("private_network_blocked",)),
    ("http://[64:ff9b::a9fe:a9fe]/", "ip_host", ("private_network_blocked",)),
    ("http://[::1]/", "ip_host", ("private_network_blocked",)),
    ("http://[::ffff:169.254.169.254]/", "ip_host", ("private_network_blocked",)),
    ("http://[fe80::1]/", "ip_host", ("private_network_blocked",)),
    ("https://api.openai.com/v1/chat", "api.openai.com", ()),
    (
        "https://example.com/?next=http%253A%252F%252Fmetadata.invalid%252Flatest",
        "example.com",
        ("metadata_endpoint_blocked",),
    ),
    (
        "https://example.com/?next=http%3A%2F%2F169.254.169.254%2F",
        "example.com",
        ("private_network_blocked", "metadata_endpoint_blocked"),
    ),
    ("https://example.com/?token=abc", "example.com", ("credential_url_blocked",)),
    ("https://example.com/safe", "example.com", ()),
    (
        "https://metadata.google.internal/computeMetadata/v1/",
        "metadata.google.internal",
        ("metadata_endpoint_blocked",),
    ),
    (
        "https://metadata.invalid/latest/meta-data",
        "metadata.invalid",
        ("metadata_endpoint_blocked",),
    ),
    ("https://metadata/latest", "metadata", ("metadata_endpoint_blocked",)),
    ("https://user:pass@example.com/", "example.com", ("credential_url_blocked",)),
)


# Hosts the legacy ``url_policy_error`` / ``is_blocked_ip`` rejected (or
# allowed). The boolean is what ``is_blocked_ip`` returned.
_IS_BLOCKED_IP_GOLDEN: tuple[tuple[str, bool], ...] = (
    ("1.1.1.1", False),
    ("10.0.0.1", True),
    ("100.64.0.1", True),
    ("127.0.0.1", True),
    ("169.254.169.254", True),
    ("172.16.0.1", True),
    ("192.168.1.1", True),
    ("8.8.8.8", False),
    ("::1", True),
    ("::ffff:169.254.169.254", True),
    ("fe80::1", True),
)


_URL_POLICY_ERROR_GOLDEN: tuple[tuple[str, str | None], ...] = (
    ("http://0177.0.0.1/", "local_url_blocked"),
    ("http://017700000001/", "local_url_blocked"),
    ("http://0x7f000001/", "local_url_blocked"),
    ("http://0xa9fea9fe/", "metadata_url_blocked"),
    ("http://10.0.0.1/admin", "private_url_blocked"),
    ("http://127.0.0.1/", "local_url_blocked"),
    ("http://169.254.169.254/latest/meta-data", "metadata_url_blocked"),
    ("http://172.16.0.1/internal", "private_url_blocked"),
    ("http://192.168.1.1/router", "private_url_blocked"),
    ("http://2130706433/", "local_url_blocked"),
    ("http://[64:ff9b::a9fe:a9fe]/", "private_url_blocked"),
    ("http://[::1]/", "local_url_blocked"),
    ("http://[::ffff:169.254.169.254]/", "local_url_blocked"),
    ("http://[fe80::1]/", "local_url_blocked"),
    ("https://api.openai.com/v1/chat", None),
    (
        "https://example.com/?next=http%253A%252F%252Fmetadata.invalid%252Flatest",
        None,
    ),
    ("https://example.com/?next=http%3A%2F%2F169.254.169.254%2F", None),
    ("https://example.com/?token=abc", "credential_url_blocked"),
    ("https://example.com/safe", None),
    ("https://metadata.google.internal/computeMetadata/v1/", "local_url_blocked"),
    ("https://metadata.invalid/latest/meta-data", None),
    ("https://metadata/latest", None),
    ("https://user:pass@example.com/", "auth_bypass_blocked"),
)


# C-6 documented strengthening — URLs whose host decodes (via legacy-IPv4
# coercion, IPv4-mapped IPv6, or NAT64) to an embedded IPv4 that lives in
# :data:`magi_agent.security.ssrf.METADATA_HOSTS`. Legacy ``sandbox/network``
# checked ``host in _METADATA_HOSTS`` AS-A-STRING (e.g. ``"0xa9fea9fe" in {...}``
# is False) so these cases got ``private_network_blocked`` only. The
# consolidation ADDITIONALLY emits ``metadata_endpoint_blocked`` because
# ``coerce_ip`` resolves the embedded IPv4 BEFORE checking the metadata set.
#
# Strict-superset direction: every legacy reason is preserved (verified by
# the loop below); the only DELTA is the addition of
# ``metadata_endpoint_blocked`` on these specific URLs — a hardening, not a
# regression. Listed explicitly so future contributors can audit at a glance.
_METADATA_STRENGTHENING_URLS: frozenset[str] = frozenset(
    {
        # Hex packed-IPv4 form of 169.254.169.254
        "http://0xa9fea9fe/",
        # IPv4-mapped IPv6 (::ffff:169.254.169.254)
        "http://[::ffff:169.254.169.254]/",
        # NAT64 (64:ff9b::169.254.169.254)
        "http://[64:ff9b::a9fe:a9fe]/",
    }
)
_EMBEDDED_METADATA_REASON = "metadata_endpoint_blocked"


@pytest.mark.parametrize("url,expected_safe_host,expected_reasons", _CLASSIFY_GOLDEN)
def test_classify_network_url_equivalence(
    url: str,
    expected_safe_host: str | None,
    expected_reasons: tuple[str, ...],
) -> None:
    """Strict-superset equivalence: every legacy reason must still appear and
    safe_host must match exactly. Extra reasons (only on the NAT64
    strengthening case) are documented."""
    from magi_agent.sandbox.network import classify_network_url

    safe_host, reasons = classify_network_url(url)
    assert safe_host == expected_safe_host, (
        f"safe_host drift on {url!r}: legacy={expected_safe_host!r} "
        f"new={safe_host!r}"
    )
    for expected in expected_reasons:
        assert expected in reasons, (
            f"REGRESSION on {url!r}: legacy emitted {expected!r}, new emits "
            f"{reasons!r}. C-6 must be strict-superset — any URL the legacy "
            f"blocked must stay blocked."
        )
    # Document allowed additions: ONLY the embedded-IPv4-metadata cases
    # (NAT64, IPv4-mapped IPv6, legacy hex-packed IPv4) may add
    # ``metadata_endpoint_blocked``. Any other added reason is a regression.
    extras = tuple(code for code in reasons if code not in expected_reasons)
    if extras:
        assert url in _METADATA_STRENGTHENING_URLS, (
            f"Unexpected extra reason on {url!r}: extras={extras!r}. C-6 only "
            f"intentionally adds reasons on the embedded-IPv4-metadata "
            f"strengthening cases: {sorted(_METADATA_STRENGTHENING_URLS)}"
        )
        assert extras == (_EMBEDDED_METADATA_REASON,), (
            f"Embedded-IPv4 metadata strengthening expected exactly "
            f"{(_EMBEDDED_METADATA_REASON,)!r}, got {extras!r}"
        )


@pytest.mark.parametrize("host,expected", _IS_BLOCKED_IP_GOLDEN)
def test_is_blocked_ip_equivalence(host: str, expected: bool) -> None:
    """``is_blocked_ip`` is byte-identical for every legacy fixture."""
    from magi_agent.web_acquisition.policy import is_blocked_ip

    assert is_blocked_ip(host) == expected, (
        f"is_blocked_ip drift on {host!r}: legacy={expected!r} "
        f"new={is_blocked_ip(host)!r}"
    )


@pytest.mark.parametrize("url,expected", _URL_POLICY_ERROR_GOLDEN)
def test_url_policy_error_equivalence(url: str, expected: str | None) -> None:
    """``url_policy_error`` reason strings are byte-identical for every
    legacy fixture. The web-acquisition reason vocabulary
    (``private_url_blocked`` / ``local_url_blocked`` / ``metadata_url_blocked`` /
    ``auth_bypass_blocked``) is preserved by the local shim — the kernel
    classifies, the shim translates."""
    from magi_agent.web_acquisition.policy import url_policy_error

    assert url_policy_error(url) == expected, (
        f"url_policy_error drift on {url!r}: legacy={expected!r} "
        f"new={url_policy_error(url)!r}"
    )
