FROM python:3.12-slim

ARG CORE_AGENT_BUILD_SHA=""
ARG CORE_AGENT_IMAGE_REPO=""
ARG CORE_AGENT_IMAGE_TAG=""
ARG CORE_AGENT_EXPECTED_IMAGE_DIGEST=""

ARG CORE_AGENT_BUILD_SHA=""
ARG CORE_AGENT_IMAGE_REPO=""
ARG CORE_AGENT_IMAGE_TAG=""
ARG CORE_AGENT_EXPECTED_IMAGE_DIGEST=""

WORKDIR /app

COPY pyproject.toml README.md ./
COPY magi_agent/ ./magi_agent/

RUN python -m pip install --no-cache-dir --upgrade pip \
  && python -m pip install --no-cache-dir ".[cli,composio,providers]"

ENV CORE_AGENT_PORT=8080 \
    CORE_AGENT_RUNTIME_ENGINE=adk-python \
    CORE_AGENT_BUILT_BUILD_SHA=${CORE_AGENT_BUILD_SHA} \
    CORE_AGENT_BUILT_IMAGE_REPO=${CORE_AGENT_IMAGE_REPO} \
    CORE_AGENT_BUILT_IMAGE_TAG=${CORE_AGENT_IMAGE_TAG} \
    CORE_AGENT_BUILT_IMAGE_DIGEST=${CORE_AGENT_EXPECTED_IMAGE_DIGEST}

EXPOSE 8080

CMD ["python", "-m", "magi_agent"]
