/**
 * `magi-agent init` — interactive config file generator.
 *
 * Prompts the user for LLM provider, model, local base URL, and API
 * key env var when needed, then writes a magi-agent.yaml file.
 */

import fs from "node:fs";
import readline from "node:readline";
import { configFilePath } from "./config.js";

const PROVIDERS = ["anthropic", "openai", "google", "openai-compatible"] as const;

const DEFAULT_MODELS: Record<string, string> = {
  anthropic: "claude-sonnet-4-6",
  openai: "gpt-4o",
  google: "gemini-2.5-pro",
  "openai-compatible": "llama3.1",
};

const DEFAULT_ENV_VARS: Record<string, string> = {
  anthropic: "ANTHROPIC_API_KEY",
  openai: "OPENAI_API_KEY",
  google: "GOOGLE_API_KEY",
  "openai-compatible": "",
};

const DEFAULT_BASE_URLS: Record<string, string> = {
  "openai-compatible": "http://127.0.0.1:11434/v1",
};

function ask(
  rl: readline.Interface,
  question: string,
): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function generateConfig(opts: {
  provider: string;
  model: string;
  apiKeyEnvVar?: string;
  baseUrl?: string;
  name: string;
}): string {
  const baseUrlLine = opts.baseUrl ? `  baseUrl: ${opts.baseUrl}\n` : "";
  const apiKeyLine = opts.apiKeyEnvVar ? `  apiKey: \${${opts.apiKeyEnvVar}}\n` : "";
  return `# Magi Configuration
# Generated by "magi-agent init"

# LLM Provider
llm:
  provider: ${opts.provider}
  model: ${opts.model}
${baseUrlLine}${apiKeyLine}

# Local/self-hosted HTTP API token.
# Use this in Magi App. Do not use your provider API key in the browser.
server:
  gatewayToken: \${MAGI_AGENT_SERVER_TOKEN}

# Channels (uncomment to enable)
# channels:
#   telegram:
#     token: \${TELEGRAM_BOT_TOKEN}
#   discord:
#     token: \${DISCORD_BOT_TOKEN}
#   webhook:
#     url: https://your-app.com/webhook
#     secret: \${WEBHOOK_SECRET}

# Hooks
hooks:
  builtin:
    factGrounding: true
    preRefusalVerifier: true
    workspaceAwareness: true
    sessionResume: true
    discipline: false

# Memory
memory:
  enabled: true
  compaction: true

# Workspace directory
workspace: ./workspace

# Agent identity
identity:
  name: "${opts.name}"
  instructions: "You are a helpful coding assistant."
`;
}

export async function runInit(): Promise<void> {
  const outPath = configFilePath();

  // Check if config already exists
  if (fs.existsSync(outPath)) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    const overwrite = await ask(
      rl,
      `\x1b[33mmagi-agent.yaml already exists.\x1b[0m Overwrite? (y/N) `,
    );
    if (overwrite.toLowerCase() !== "y") {
      rl.close();
      console.log("Aborted.");
      return;
    }
    rl.close();
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log("");
  console.log("\x1b[1mMagi — Configuration\x1b[0m");
  console.log("");

  // Provider
  const providerInput = await ask(
    rl,
    `LLM provider (${PROVIDERS.join(" / ")}) [\x1b[2manthropic\x1b[0m]: `,
  );
  const provider: typeof PROVIDERS[number] = PROVIDERS.includes(providerInput as typeof PROVIDERS[number])
    ? providerInput as typeof PROVIDERS[number]
    : "anthropic";

  // Model
  const defaultModel = DEFAULT_MODELS[provider] ?? "claude-sonnet-4-6";
  const modelInput = await ask(
    rl,
    `Model [\x1b[2m${defaultModel}\x1b[0m]: `,
  );
  const model = modelInput || defaultModel;

  // Base URL
  const defaultBaseUrl = DEFAULT_BASE_URLS[provider];
  const baseUrlInput = defaultBaseUrl
    ? await ask(
        rl,
        `OpenAI-compatible base URL [\x1b[2m${defaultBaseUrl}\x1b[0m]: `,
      )
    : "";
  const baseUrl = defaultBaseUrl ? baseUrlInput || defaultBaseUrl : undefined;

  // API key env var
  const defaultEnvVar = DEFAULT_ENV_VARS[provider] ?? "LLM_API_KEY";
  const envVarInput = await ask(
    rl,
    provider === "openai-compatible"
      ? `API key env variable, optional for local no-auth servers [\x1b[2mnone\x1b[0m]: `
      : `API key env variable [\x1b[2m${defaultEnvVar}\x1b[0m]: `,
  );
  const apiKeyEnvVar =
    provider === "openai-compatible" ? envVarInput || undefined : envVarInput || defaultEnvVar;

  // Agent name
  const nameInput = await ask(
    rl,
    `Agent name [\x1b[2mMagi\x1b[0m]: `,
  );
  const name = nameInput || "Magi";

  rl.close();

  const content = generateConfig({
    provider,
    model,
    apiKeyEnvVar,
    baseUrl,
    name,
  });

  fs.writeFileSync(outPath, content, "utf-8");

  console.log("");
  console.log(`\x1b[32mCreated\x1b[0m ${outPath}`);
  console.log("");
  console.log(`Next steps:`);
  if (apiKeyEnvVar) {
    console.log(`  1. Set your API key:  export ${apiKeyEnvVar}=sk-...`);
  } else {
    console.log(`  1. Start your local model server, for example: ollama serve`);
  }
  console.log(`  2. Set an app token:  export MAGI_AGENT_SERVER_TOKEN=$(openssl rand -hex 24)`);
  console.log(`  3. Start interactive: magi-agent chat`);
  console.log(`  4. Or run as server:  magi-agent serve --port 8080`);
  console.log("");
}
