import fs from "node:fs/promises";
import path from "node:path";
import type { IncomingMessage, ServerResponse } from "node:http";
import { parse } from "yaml";
import {
  authorizeBearer,
  readJsonBody,
  route,
  writeJson,
  type HttpServerCtx,
  type RouteHandler,
} from "./_helpers.js";

const PROVIDERS = ["anthropic", "openai", "google", "openai-compatible"] as const;

type Provider = typeof PROVIDERS[number];

interface AppConfigInput {
  llm?: {
    provider?: string;
    model?: string;
    baseUrl?: string;
    apiKeyEnvVar?: string;
    capabilities?: Record<string, unknown>;
  };
  server?: {
    gatewayTokenEnvVar?: string;
  };
  workspace?: string;
}

function configPath(): string {
  return process.env.MAGI_AGENT_CONFIG_PATH || path.resolve(process.cwd(), "magi-agent.yaml");
}

function envVarRef(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const match = value.trim().match(/^\$\{([A-Z_][A-Z0-9_]*)\}$/);
  return match?.[1];
}

function isProvider(value: string): value is Provider {
  return PROVIDERS.includes(value as Provider);
}

function safeEnvVar(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return /^[A-Z_][A-Z0-9_]*$/.test(trimmed) ? trimmed : undefined;
}

function readObject(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function sanitizeConfig(raw: string, filePath: string): Record<string, unknown> {
  const parsed = readObject(parse(raw));
  const llm = readObject(parsed.llm);
  const server = readObject(parsed.server);
  const apiKey = typeof llm.apiKey === "string" ? llm.apiKey.trim() : "";
  const gatewayToken =
    typeof server.gatewayToken === "string" ? server.gatewayToken.trim() : "";
  return {
    path: filePath,
    exists: true,
    config: {
      llm: {
        provider: typeof llm.provider === "string" ? llm.provider : undefined,
        model: typeof llm.model === "string" ? llm.model : undefined,
        baseUrl: typeof llm.baseUrl === "string" ? llm.baseUrl : undefined,
        apiKeySet: apiKey.length > 0,
        apiKeyEnvVar: envVarRef(apiKey),
        capabilities: readObject(llm.capabilities),
      },
      server: {
        gatewayTokenSet: gatewayToken.length > 0,
        gatewayTokenEnvVar: envVarRef(gatewayToken),
      },
      workspace: typeof parsed.workspace === "string" ? parsed.workspace : undefined,
      identity: readObject(parsed.identity),
    },
  };
}

async function handleGetConfig(
  req: IncomingMessage,
  res: ServerResponse,
  _match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const filePath = configPath();
  let raw = "";
  try {
    raw = await fs.readFile(filePath, "utf8");
  } catch {
    writeJson(res, 200, { ok: true, path: filePath, exists: false, config: null });
    return;
  }
  writeJson(res, 200, { ok: true, ...sanitizeConfig(raw, filePath) });
}

function capabilityLines(capabilities: Record<string, unknown> | undefined): string[] {
  if (!capabilities || typeof capabilities !== "object") return [];
  const out: string[] = [];
  const fields = [
    "contextWindow",
    "maxOutputTokens",
    "supportsThinking",
    "inputUsdPerMtok",
    "outputUsdPerMtok",
  ] as const;
  for (const field of fields) {
    const value = capabilities[field];
    if (typeof value === "number" && Number.isFinite(value)) {
      out.push(`    ${field}: ${Math.floor(value)}`);
    } else if (typeof value === "boolean") {
      out.push(`    ${field}: ${value}`);
    }
  }
  return out;
}

function renderConfig(input: AppConfigInput): string {
  const llm = input.llm ?? {};
  const provider = typeof llm.provider === "string" && isProvider(llm.provider)
    ? llm.provider
    : "openai-compatible";
  const model = typeof llm.model === "string" && llm.model.trim()
    ? llm.model.trim()
    : "llama3.1";
  const lines = [
    "# Magi Configuration",
    "# Generated by Magi App settings.",
    "",
    "llm:",
    `  provider: ${provider}`,
    `  model: ${model}`,
  ];
  if (typeof llm.baseUrl === "string" && llm.baseUrl.trim()) {
    lines.push(`  baseUrl: ${llm.baseUrl.trim()}`);
  }
  const apiKeyEnvVar = safeEnvVar(llm.apiKeyEnvVar);
  if (apiKeyEnvVar) {
    lines.push(`  apiKey: \${${apiKeyEnvVar}}`);
  }
  const caps = capabilityLines(llm.capabilities);
  if (caps.length > 0) {
    lines.push("  capabilities:", ...caps);
  }
  const serverTokenEnvVar = safeEnvVar(input.server?.gatewayTokenEnvVar);
  if (serverTokenEnvVar) {
    lines.push("", "server:", `  gatewayToken: \${${serverTokenEnvVar}}`);
  }
  lines.push("", `workspace: ${input.workspace?.trim() || "./workspace"}`, "");
  return lines.join("\n");
}

async function handlePutConfig(
  req: IncomingMessage,
  res: ServerResponse,
  _match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const body = readObject(await readJsonBody(req)) as AppConfigInput;
  const provider = body.llm?.provider;
  if (provider !== undefined && (!isProvider(provider))) {
    writeJson(res, 400, { error: "invalid_provider" });
    return;
  }
  const filePath = configPath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, renderConfig(body), "utf8");
  writeJson(res, 200, { ok: true, path: filePath });
}

function rulesDir(ctx: HttpServerCtx): string {
  return path.join(ctx.agent.config.workspaceRoot, "harness-rules");
}

function ruleNameFromMatch(match: RegExpMatchArray): string | null {
  let decoded = "";
  try {
    decoded = decodeURIComponent(match[1] ?? "");
  } catch {
    return null;
  }
  if (!/^[A-Za-z0-9._-]+\.md$/.test(decoded) || decoded.includes("..")) {
    return null;
  }
  return decoded;
}

async function handleListRules(
  req: IncomingMessage,
  res: ServerResponse,
  _match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const dir = rulesDir(ctx);
  await fs.mkdir(dir, { recursive: true });
  const names = (await fs.readdir(dir)).filter((name) => /^[A-Za-z0-9._-]+\.md$/.test(name)).sort();
  const rules = await Promise.all(
    names.map(async (name) => {
      const stat = await fs.stat(path.join(dir, name));
      return { name, sizeBytes: stat.size };
    }),
  );
  writeJson(res, 200, { ok: true, rules });
}

async function handleGetRule(
  req: IncomingMessage,
  res: ServerResponse,
  match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const name = ruleNameFromMatch(match);
  if (!name) {
    writeJson(res, 400, { error: "invalid_rule_name" });
    return;
  }
  try {
    const content = await fs.readFile(path.join(rulesDir(ctx), name), "utf8");
    writeJson(res, 200, { ok: true, name, content });
  } catch {
    writeJson(res, 404, { error: "not_found" });
  }
}

async function handlePutRule(
  req: IncomingMessage,
  res: ServerResponse,
  match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const name = ruleNameFromMatch(match);
  if (!name) {
    writeJson(res, 400, { error: "invalid_rule_name" });
    return;
  }
  const body = readObject(await readJsonBody(req));
  if (typeof body.content !== "string") {
    writeJson(res, 400, { error: "missing_content" });
    return;
  }
  const dir = rulesDir(ctx);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, name), body.content, "utf8");
  writeJson(res, 200, { ok: true, name });
}

async function handleDeleteRule(
  req: IncomingMessage,
  res: ServerResponse,
  match: RegExpMatchArray,
  ctx: HttpServerCtx,
): Promise<void> {
  if (!authorizeBearer(req, res, ctx)) return;
  const name = ruleNameFromMatch(match);
  if (!name) {
    writeJson(res, 400, { error: "invalid_rule_name" });
    return;
  }
  await fs.rm(path.join(rulesDir(ctx), name), { force: true });
  writeJson(res, 200, { ok: true, name });
}

export const appSettingsRoutes: RouteHandler[] = [
  route("GET", /^\/v1\/app\/config(?:\?.*)?$/, handleGetConfig),
  route("PUT", /^\/v1\/app\/config(?:\?.*)?$/, handlePutConfig),
  route("GET", /^\/v1\/app\/harness-rules(?:\?.*)?$/, handleListRules),
  route("GET", /^\/v1\/app\/harness-rules\/([^/?]+)(?:\?.*)?$/, handleGetRule),
  route("PUT", /^\/v1\/app\/harness-rules\/([^/?]+)(?:\?.*)?$/, handlePutRule),
  route("DELETE", /^\/v1\/app\/harness-rules\/([^/?]+)(?:\?.*)?$/, handleDeleteRule),
];
