#!/usr/bin/env bash
# Build the restored web dashboard (apps/web static export) and sync the built
# bundle into the Python package so `magi-agent serve` can serve it at
# /dashboard with no Node runtime.
#
# The committed bundle at magi_agent/web_dashboard/ is generated by this script.
# Re-run it after changing anything under apps/web/ and commit the result.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB="$ROOT/apps/web"
DEST="$ROOT/magi_agent/web_dashboard"

cd "$WEB"
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi
npm run build

rm -rf "$DEST"
cp -R "$WEB/dist" "$DEST"
echo "Synced $WEB/dist -> $DEST"
