from __future__ import annotations

from importlib import import_module
from typing import Any

from .builtin import (
    BuiltInEvidenceType,
    ProducerSurface,
    builtin_evidence_by_type,
    builtin_evidence_catalog,
    builtin_evidence_types,
)
from .contracts import (
    EVIDENCE_REGEX_CANDIDATE_LIMIT,
    EvidenceContractEngine,
    evaluate_evidence_contract,
)
from .extractors import (
    CustomEvidenceExtractor,
    CustomEvidenceExtractorConfig,
    CustomEvidenceExtractorSource,
    CustomEvidenceExtractorSourceKind,
    CustomEvidenceFieldMapping,
    CustomEvidenceSuccessCondition,
)
from .ledger import EvidenceLedger, EvidenceLedgerEntry, EvidenceLedgerEntryKind
from .types import (
    EvidenceAfter,
    EvidenceAgentRole,
    EvidenceContract,
    EvidenceContractFailure,
    EvidenceContractScopeMetadata,
    EvidenceContractVerdict,
    EvidenceEnforcement,
    EvidenceFailureCode,
    EvidenceFieldMatcher,
    EvidenceOnMissing,
    EvidenceRecord,
    EvidenceRequirement,
    EvidenceRunOn,
    EvidenceSource,
    EvidenceSourceKind,
    EvidenceSpawnDepthRange,
    EvidenceStatus,
    EvidenceTrigger,
    EvidenceVerdictState,
)

_LAZY_EXPORTS = {
    "CODING_VERIFICATION_AUDIT_CONTRACT_ID": (
        ".coding_verification",
        "CODING_VERIFICATION_AUDIT_CONTRACT_ID",
    ),
    "CODING_VERIFICATION_AUDIT_VERIFIER_ID": (
        ".coding_verification",
        "CODING_VERIFICATION_AUDIT_VERIFIER_ID",
    ),
    "ChildEvidenceEnvelope": (".subagent", "ChildEvidenceEnvelope"),
    "ChildEvidenceStatus": (".subagent", "ChildEvidenceStatus"),
    "ChildRuntimeEnvelope": (".child_runtime_envelope", "ChildRuntimeEnvelope"),
    "ChildRuntimeEnvelopeAuthorityFlags": (
        ".child_runtime_envelope",
        "ChildRuntimeEnvelopeAuthorityFlags",
    ),
    "PublicChildRuntimeEnvelopeProjection": (
        ".child_runtime_envelope",
        "PublicChildRuntimeEnvelopeProjection",
    ),
    "CodingVerificationAuditAttachmentFlags": (
        ".coding_verification",
        "CodingVerificationAuditAttachmentFlags",
    ),
    "CodingVerificationAuditRequest": (
        ".coding_verification",
        "CodingVerificationAuditRequest",
    ),
    "CodingVerificationAuditResult": (
        ".coding_verification",
        "CodingVerificationAuditResult",
    ),
    "CustomChildEvidenceSchema": (".subagent", "CustomChildEvidenceSchema"),
    "AuditLedgerMode": (".ledger_semantics", "AuditLedgerMode"),
    "ContentAddressedLedger": (".ledger_semantics", "ContentAddressedLedger"),
    "ContentAddressedLedgerRecord": (".ledger_semantics", "ContentAddressedLedgerRecord"),
    "DelegatedEvidenceRequirement": (".subagent", "DelegatedEvidenceRequirement"),
    "DelegatedRequirementMatch": (".subagent", "DelegatedRequirementMatch"),
    "EvidenceBoundaryLedgerRef": (".subagent", "EvidenceBoundaryLedgerRef"),
    "EvidenceDelegationMode": (".subagent", "EvidenceDelegationMode"),
    "EvidenceProvenance": (".subagent", "EvidenceProvenance"),
    "ExecutionBoundaryIdentity": (".subagent", "ExecutionBoundaryIdentity"),
    "LedgerRecordKind": (".ledger_semantics", "LedgerRecordKind"),
    "LedgerVerificationReport": (".ledger_semantics", "LedgerVerificationReport"),
    "LlmAssistedPolicyAction": (".validator_taxonomy", "LlmAssistedPolicyAction"),
    "OPENMAGI_RUNTIME_ENVELOPE_ISSUER": (".subagent", "OPENMAGI_RUNTIME_ENVELOPE_ISSUER"),
    "ParentEvidenceAggregation": (".subagent", "ParentEvidenceAggregation"),
    "ParentEvidenceState": (".subagent", "ParentEvidenceState"),
    "PolicySnapshotCompatibility": (".subagent", "PolicySnapshotCompatibility"),
    "PropagatedEvidenceRecord": (".subagent", "PropagatedEvidenceRecord"),
    "PublicChildAggregateReport": (".subagent", "PublicChildAggregateReport"),
    "PublicChildEvidenceReport": (".subagent", "PublicChildEvidenceReport"),
    "CalculationEvidenceReceipt": (".runtime_receipts", "CalculationEvidenceReceipt"),
    "REQUIRED_SUBAGENT_EVIDENCE_WARNINGS": (".subagent", "REQUIRED_SUBAGENT_EVIDENCE_WARNINGS"),
    "ReceiptAuthorityFlags": (".runtime_receipts", "ReceiptAuthorityFlags"),
    "RedactionStatus": (".runtime_receipts", "RedactionStatus"),
    "SourceEvidenceReceipt": (".runtime_receipts", "SourceEvidenceReceipt"),
    "ToolExecutionReceipt": (".runtime_receipts", "ToolExecutionReceipt"),
    "ToolReceiptStatus": (".runtime_receipts", "ToolReceiptStatus"),
    "ValidatorAction": (".validator_taxonomy", "ValidatorAction"),
    "ValidatorPolicy": (".validator_taxonomy", "ValidatorPolicy"),
    "ValidatorPolicyDecision": (".validator_taxonomy", "ValidatorPolicyDecision"),
    "ValidatorResult": (".validator_taxonomy", "ValidatorResult"),
    "ValidatorSupportStatus": (".validator_taxonomy", "ValidatorSupportStatus"),
    "ValidatorTrustClass": (".validator_taxonomy", "ValidatorTrustClass"),
    "aggregate_child_evidence": (".subagent", "aggregate_child_evidence"),
    "append_ledger_record": (".ledger_semantics", "append_ledger_record"),
    "apply_validator_policy": (".validator_taxonomy", "apply_validator_policy"),
    "build_coding_verification_audit_contract": (
        ".coding_verification",
        "build_coding_verification_audit_contract",
    ),
    "evaluate_coding_verification_audit": (
        ".coding_verification",
        "evaluate_coding_verification_audit",
    ),
    "match_delegated_requirement": (".subagent", "match_delegated_requirement"),
    "natural_language_summary_as_evidence": (".subagent", "natural_language_summary_as_evidence"),
    "project_child_runtime_envelope": (
        ".child_runtime_envelope",
        "project_child_runtime_envelope",
    ),
    "public_child_aggregate_report": (".subagent", "public_child_aggregate_report"),
    "runtime_envelope_satisfies_delegated_evidence_metadata": (
        ".child_runtime_envelope",
        "runtime_envelope_satisfies_delegated_evidence_metadata",
    ),
    "verify_ledger_chain": (".ledger_semantics", "verify_ledger_chain"),
}

__all__ = [
    "BuiltInEvidenceType",
    "CODING_VERIFICATION_AUDIT_CONTRACT_ID",
    "CODING_VERIFICATION_AUDIT_VERIFIER_ID",
    "CustomEvidenceExtractor",
    "CustomEvidenceExtractorConfig",
    "CustomEvidenceExtractorSource",
    "CustomEvidenceExtractorSourceKind",
    "CustomEvidenceFieldMapping",
    "CustomEvidenceSuccessCondition",
    "ChildEvidenceEnvelope",
    "ChildEvidenceStatus",
    "ChildRuntimeEnvelope",
    "ChildRuntimeEnvelopeAuthorityFlags",
    "ContentAddressedLedger",
    "ContentAddressedLedgerRecord",
    "CodingVerificationAuditAttachmentFlags",
    "CodingVerificationAuditRequest",
    "CodingVerificationAuditResult",
    "CalculationEvidenceReceipt",
    "EVIDENCE_REGEX_CANDIDATE_LIMIT",
    "CustomChildEvidenceSchema",
    "DelegatedEvidenceRequirement",
    "DelegatedRequirementMatch",
    "EvidenceAfter",
    "EvidenceAgentRole",
    "EvidenceContract",
    "EvidenceContractEngine",
    "EvidenceContractFailure",
    "EvidenceContractScopeMetadata",
    "EvidenceContractVerdict",
    "EvidenceBoundaryLedgerRef",
    "EvidenceDelegationMode",
    "EvidenceEnforcement",
    "EvidenceFailureCode",
    "EvidenceFieldMatcher",
    "EvidenceLedger",
    "EvidenceLedgerEntry",
    "EvidenceLedgerEntryKind",
    "EvidenceOnMissing",
    "EvidenceProvenance",
    "EvidenceRecord",
    "EvidenceRequirement",
    "EvidenceRunOn",
    "EvidenceSource",
    "EvidenceSourceKind",
    "EvidenceSpawnDepthRange",
    "EvidenceStatus",
    "EvidenceTrigger",
    "EvidenceVerdictState",
    "ExecutionBoundaryIdentity",
    "AuditLedgerMode",
    "LedgerRecordKind",
    "LedgerVerificationReport",
    "LlmAssistedPolicyAction",
    "OPENMAGI_RUNTIME_ENVELOPE_ISSUER",
    "ParentEvidenceAggregation",
    "ParentEvidenceState",
    "PolicySnapshotCompatibility",
    "ProducerSurface",
    "PropagatedEvidenceRecord",
    "PublicChildRuntimeEnvelopeProjection",
    "PublicChildAggregateReport",
    "PublicChildEvidenceReport",
    "REQUIRED_SUBAGENT_EVIDENCE_WARNINGS",
    "ReceiptAuthorityFlags",
    "RedactionStatus",
    "SourceEvidenceReceipt",
    "ToolExecutionReceipt",
    "ToolReceiptStatus",
    "ValidatorAction",
    "ValidatorPolicy",
    "ValidatorPolicyDecision",
    "ValidatorResult",
    "ValidatorSupportStatus",
    "ValidatorTrustClass",
    "aggregate_child_evidence",
    "append_ledger_record",
    "apply_validator_policy",
    "build_coding_verification_audit_contract",
    "builtin_evidence_by_type",
    "builtin_evidence_catalog",
    "builtin_evidence_types",
    "evaluate_evidence_contract",
    "evaluate_coding_verification_audit",
    "match_delegated_requirement",
    "natural_language_summary_as_evidence",
    "project_child_runtime_envelope",
    "public_child_aggregate_report",
    "runtime_envelope_satisfies_delegated_evidence_metadata",
    "verify_ledger_chain",
]


def __getattr__(name: str) -> Any:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))
